import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import type { AgentConfig, AgentJD } from '../types/index.js';

interface AgentEntry {
  name: string;
  org: string;
  configPath: string;
  agentDir: string;
  jd: AgentJD;
}

function readAgentConfigs(baseDir: string): AgentEntry[] {
  const entries: AgentEntry[] = [];
  // Search orgs/*/agents/*/config.json
  const orgsDir = join(baseDir, 'orgs');
  if (!existsSync(orgsDir)) return entries;
  for (const org of readdirSync(orgsDir)) {
    const agentsDir = join(orgsDir, org, 'agents');
    if (!existsSync(agentsDir)) continue;
    for (const agentName of readdirSync(agentsDir)) {
      const configPath = join(agentsDir, agentName, 'config.json');
      if (!existsSync(configPath)) continue;
      try {
        const config: AgentConfig = JSON.parse(readFileSync(configPath, 'utf-8'));
        if (config.jd && config.jd.title) {
          entries.push({ name: agentName, org, configPath, agentDir: dirname(configPath), jd: config.jd });
        }
      } catch { /* corrupt config — skip */ }
    }
  }
  return entries;
}

function buildRegistry(entries: AgentEntry[], forOrg: string): string {
  const lines = ['# Agent Directory', '*Auto-generated by `officeos sync-jds`. Do not edit.*', ''];
  for (const e of entries) {
    const tag = e.org === forOrg ? '' : ' _(shared)_';
    lines.push(`## ${e.name} — ${e.jd.title}${tag}`);
    lines.push(`${e.jd.description}`);
    lines.push('');
    if (e.jd.responsibilities.length) {
      lines.push('**Handles:**');
      for (const r of e.jd.responsibilities) lines.push(`- ${r}`);
      lines.push('');
    }
    if (e.jd.provides.length) lines.push(`**Provides:** ${e.jd.provides.join(', ')}`);
    if (e.jd.needs.length) lines.push(`**Needs:** ${e.jd.needs.join(', ')}`);
    if (e.jd.keywords.length) lines.push(`**Keywords:** ${e.jd.keywords.join(', ')}`);
    if (e.jd.out_of_scope?.length) lines.push(`**Out of scope:** ${e.jd.out_of_scope.join(', ')}`);
    lines.push('');
  }
  return lines.join('\n');
}

function buildCollaborators(agent: AgentEntry, all: AgentEntry[]): string | null {
  const collabs = all.filter(other => other.name !== agent.name && (
    agent.jd.needs.some(need =>
      other.jd.provides.some(prov => prov.toLowerCase().includes(need.toLowerCase()) || need.toLowerCase().includes(prov.toLowerCase()))
    )
  ));
  if (!collabs.length) return null;
  const lines = ['# Collaborators', '*Auto-written by `officeos sync-jds`. Updated when agents added/changed.*', ''];
  for (const c of collabs) {
    const relevantProvides = c.jd.provides.filter(prov =>
      agent.jd.needs.some(need => prov.toLowerCase().includes(need.toLowerCase()) || need.toLowerCase().includes(prov.toLowerCase()))
    );
    lines.push(`## ${c.name} — ${c.jd.title}`);
    if (relevantProvides.length) lines.push(`**Provides you:** ${relevantProvides.join(', ')}`);
    if (c.jd.keywords.length) lines.push(`**Use when:** ${c.jd.keywords.slice(0, 3).join(', ')}`);
    lines.push(`**Route via:** \`officeos bus send-message ${c.name} 1 'ROUTED_QUERY: <msg>'\``);
    lines.push('');
  }
  return lines.join('\n');
}

export function syncJDs(ctxRoot?: string): { registry: number; collaborators: number } {
  const baseDir = ctxRoot || process.env.CTX_ROOT || process.cwd();
  const entries = readAgentConfigs(baseDir);
  if (!entries.length) {
    console.log('No agents with JD blocks found. Add jd fields to agent config.json files.');
    return { registry: 0, collaborators: 0 };
  }

  // Each orchestrator sees its own org's agents + shared agents from other orgs.
  // Team-internal specialists never leak into another team's registry.
  const visibleTo = (orchOrg: string) =>
    entries.filter(e => e.org === orchOrg || e.jd.shared);

  const orchAgents = entries.filter(e => e.name.toLowerCase().includes('orch'));

  // Write an org-scoped registry to each orchestrator's dir
  for (const orch of orchAgents) {
    const registry = buildRegistry(visibleTo(orch.org), orch.org);
    const registryPath = join(orch.agentDir, 'jds-registry.md');
    writeFileSync(registryPath, registry, 'utf-8');
    console.log(`Wrote registry (${orch.org}) → ${registryPath}`);
  }

  // If no orch found, write a full registry to the first agent's org dir
  if (!orchAgents.length && entries.length) {
    const orgDir = dirname(dirname(entries[0].agentDir));
    const registry = buildRegistry(entries, entries[0].org);
    const registryPath = join(orgDir, 'jds-registry.md');
    writeFileSync(registryPath, registry, 'utf-8');
    console.log(`Wrote registry → ${registryPath}`);
  }

  // Write collaborators to matched agents — scoped to reachable peers
  // (same org + shared agents), matching the registry visibility model.
  let collabCount = 0;
  for (const entry of entries) {
    const collabContent = buildCollaborators(entry, visibleTo(entry.org));
    if (collabContent) {
      const memDir = join(entry.agentDir, 'memory');
      mkdirSync(memDir, { recursive: true });
      writeFileSync(join(memDir, 'collaborators.md'), collabContent, 'utf-8');
      collabCount++;
    }
  }

  console.log(`sync-jds: ${entries.length} agents, registry written, ${collabCount} collaborator files updated`);
  return { registry: entries.length, collaborators: collabCount };
}
